from manim import *
class TitleCard(Scene):
    def construct(self):
        p = Circle().shift(UP)
        np = Circle().scale(2)
        complete = Circle().scale(4).shift(DOWN*4)
        self.play(ShowCreation(p))
        self.wait(1)
        self.play(ShowCreation(np))
        self.wait(1)
        self.play(ShowCreation(complete))
        self.wait(2)
        title = TextMobject("Title Goes Here").scale(2).to_edge(edge=UP)
        self.play(Write(title))
        temp = Circle().shift(UP)
        self.wait(1)
        self.play(ReplacementTransform(p, np))
        self.wait(2)
        self.play(ReplacementTransform(p, temp))
        self.wait(3)

class WhatIsP(Scene):
    def construct(self):
        question = TextMobject("What is $P$?").scale(2).to_corner(corner=UP+LEFT)
        underline = Line().set_length(question.get_width()).next_to(question, direction=DOWN)
        self.play(Write(question))
        self.play(ShowCreation(underline))
        self.wait(1)
        alg = TextMobject("$\\texttt{A}$").scale(2)
        self.play(Write(alg))
        self.play(ApplyMethod(alg.to_edge, LEFT))
        bracket = TextMobject("$$\in \\begin{cases} O(1) \\\ O(n) \\\ O(n^c) \\end{cases}$$").next_to(alg, direction=RIGHT)
        self.play(Write(bracket))
        self.wait(1)
        self.play(FadeOut(bracket), FadeOut(alg))
        self.wait(1)